version: '2'

services:
  zookeeper:
    image: 'guizasy/openshift-zookeeper'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

volumes:
  zookeeper_data:
    driver: local
